### ISSUE TITLE
Popup text field UI issue

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Prabbi-Internal-Store-dev-Speed#1]
Bug - Text Field Ui issue on popup on homepage.
Exp - Sugg - Placeholder should be in center.
- Field box UI hieght and width should be same.
Ref Link - https://nimb.ws/smMnVx

**Comment by ui-monikasingh** [comment]
@ankitcedcoss coming from app.. it will be removed after it will go live

**Comment by ankitcedcoss** [comment]
Closing on Not Required
