### ISSUE TITLE
Dynamic search stopped working 

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Prabbi-Internal-Store-dev-Speed#15]
Bug - Dynamic search no working on Preview after speed work.
Exp - Dynamic search should work on preview.
Ref Link - https://drive.google.com/file/d/1eCbq7iIGZ0FYV4e6jrD54GVZ0X554u2i/view

**Comment by devabulabbas** [comment]
@ankitcedcoss resolved

**Comment by ankitcedcoss** [comment]
Bug Not Fixed 
@devabulabbas Please Check Video
- Dynamic search not working on search page.
- Pop dettaching UI issue on mobile.

- https://drive.google.com/file/d/1lvma_aRvoDh0_fuAMt_J17FuJbMuCQ6P/view

**Comment by ankitcedcoss** [comment]
Bug Fixed
