### ISSUE TITLE
Padding issue on banner on collection page

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Prabbi-Internal-Store-dev-Speed#2]
Bug - padding not showing on top on banner on collection page.
Exp - Add padding above on flag showing on collections page.
Ref Link - https://drive.google.com/file/d/11OC8VaWMIUQhyIQNdPsKtJxeEaaPmFTr/view

**Comment by ui-monikasingh** [comment]
@ankitcedcoss as per client requirement

**Comment by ankitcedcoss** [comment]
Closing on Not Required
