### ISSUE TITLE
Service Images and text Ui issue on Homepage

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Prabbi-Internal-Store-dev-Speed#3]
Bug - Services icons and text not aligned properly on page.
Exp - add proper spacing between line height and text should be proper align in row.
- Image should be visible in center on page.
Ref Link - https://nimb.ws/faiIVH

**Comment by ui-monikasingh** [comment]
@ankitcedcoss you are checking live website

**Comment by ankitcedcoss** [comment]
Bug Fixed
