### ISSUE TITLE
View all button on search not visible on responsive - Tab and Mobile

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Prabbi-Internal-Store-dev-Speed#5]
Bug - View all button not showing on mobile and tab UI.
Exp - When user search any product then view all button not visible on page.
Ref link - https://drive.google.com/file/d/1AYjn35Ni9kZqJs6Z1hAtNUc5ZbxksB5P/view

**Comment by ui-monikasingh** [comment]
@ankitcedcoss that's why collection  option is given in responsive

**Comment by ankitcedcoss** [comment]
Closing on Nor required
