### ISSUE TITLE
Overlapping issue on product page in responsive - Mobile UI

### ISSUE THREAD

**Issue by ankitcedcoss** [stores-cedcommerce/Prabbi-Internal-Store-dev-Speed#8]
Bug - Add to cart button overlapping on share drawer options.
Exp - share link drawer should get visible above from add to cart button.
Ref Link - https://drive.google.com/file/d/1ZDL-edkjWo4vsCz5oFhbUexPdHVhlCLM/view

**Comment by ui-monikasingh** [comment]
@ankitcedcoss coming from app will removed once website will go live

**Comment by ui-monikasingh** [comment]
@ankitcedcoss coming from app

**Comment by ankitcedcoss** [comment]
Closing on Not Required
